kind: Service
apiVersion: v1
metadata:
  name:  flask-docker-service
spec:
  type: NodePort
  selector:
    app:  flask-docker
  ports:
  - protocol: TCP
    port: 5000
    nodePort: 30080

---

apiVersion:  extensions/v1beta1
kind: Deployment
metadata:
  name: flask-docker-deployment
  labels:
    app: flask-docker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask-docker
  template:
    metadata:
      labels:
        app: flask-docker
    spec:
      containers:
      - name: flask-docker
        image: 756757677343.dkr.ecr.us-east-1.amazonaws.com/terraform-eks-demo:$BUILD_NUMBER
        ports:
        - containerPort: 5000
